/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_geek_linedetcet_util_LineDetectUtils */

#ifndef _Included_com_geek_linedetcet_util_LineDetectUtils
#define _Included_com_geek_linedetcet_util_LineDetectUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_geek_linedetcet_util_LineDetectUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_geek_linedetcet_util_LineDetectUtils_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_geek_linedetcet_util_LineDetectUtils
 * Method:    getAlphaLine
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_com_geek_linedetcet_util_LineDetectUtils_getAlphaLine
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_geek_linedetcet_util_LineDetectUtils
 * Method:    getAlphaValueAndLocation
 * Signature: ([BII[BIID[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_geek_linedetcet_util_LineDetectUtils_getAlphaValueAndLocation
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint, jdouble, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
